### ISSUE TITLE
Running demo project on clean SF dev org causes compile issues

### ISSUE THREAD

**Issue by MathieuDiepman** [apexsharp/apexsharp#16]
- System.DateTime object is not recognized due to missing System namespace. Can be fixed by including the System namespace in ModelGen.cs
- DandBCompany is not generated but referenced by Account.cs in SObject

**Comment by MathieuDiepman** [comment]
issue is resolved in dev branch

**Comment by yallie** [comment]
@MathieuDiepman — thanks for reporting!
