### ISSUE TITLE
Compiling with Rider in Linux

### ISSUE THREAD

**Issue by derekforeman** [apexsharp/apexsharp#2]
The project fails to compile with Rider when running in Linux. Running dotnet restore, in each project directory seems to clear this error and allow for compiling. 

After correcting the paths in Setup.cs for linux another error is thrown. 
  Microsoft.Common.CurrentVersion.targets(2924, 5): [MSB3552] Resource file "**/*.resx" cannot be found.

Prior to changing the paths, the project did run once, but failed with a null path. 
{System.ArgumentException: Path cannot be the empty string or all whitespace.
Parameter name: path
   at System.IO.Directory.CreateDirectory(String path)
   at ApexSharpApi.ConnectionUtil.CreateSession(ApexSharpConfig config) in /home/dforeman/Projects/apexsharp/ApexSharpApi/ConnectionUtil.cs:line 63
   at ApexSharpApi.ApexSharp.CreateSession() in /home/dforeman/Projects/apexsharp/ApexSharpApi/ApexSharp.cs:line 30
   at Demo.Setup.Init() in /home/dforeman/Projects/apexsharp/Demo/Setup.cs:line 38
   at Demo.Program.Main(String[] args) in /home/dforeman/Projects/apexsharp/Demo/Program.cs:line 15}

I think this is more related to Rider itself than the project, but do not have a resolution at the moment. If anyone else gets it to run, I'd appreciate knowing how.

**Comment by jayonsoftware** [comment]
In /home/dforeman/Projects/apexsharp/ApexSharpApi/ConnectionUtil.cs:line 63

Can you change the method ApexSharpConfig CreateSession

` public static ApexSharpConfig CreateSession(ApexSharpConfig config)
        {
            config.SalesForceUrl = config.SalesForceUrl + "services/Soap/c/" + config.SalesForceApiVersion + ".0/";
            config = GetNewConnection(config);

            string json = JsonConvert.SerializeObject(config, Formatting.Indented);
            Console.WriteLine(Path.GetDirectoryName(config.ConfigLocation));
            Directory.CreateDirectory(Path.GetDirectoryName(config.ConfigLocation));
            File.WriteAllText(config.ConfigLocation, json);

            return config;
        }`

Jay

**Comment by derekforeman** [comment]
It's failing to build at all in rider now, cleaned and rebuilt. 
Microsoft.Common.CurrentVersion.targets(2924, 5): [MSB3552] Resource file "**/*.resx" cannot be found.

I'll pick it up in OS X tomorrow.

**Comment by jayonsoftware** [comment]
Can you try the code from the dev branch.

**Comment by jayonsoftware** [comment]
Looks like its a bug on Rider. 

![image](https://user-images.githubusercontent.com/1304943/34027541-5084c2c2-e12b-11e7-88bb-9adecb305d56.png)

**Comment by derekforeman** [comment]
The dev branch does appear to compile in rider on linux and generates offline objects as expected, though the paths are messy on non windows environments.
