### ISSUE TITLE
SObject case senstivities on methods

### ISSUE THREAD

**Issue by tyschacht** [apexsharp/apexsharp#9]
When doing Apex -> C#, all SObject method calls in apex are brought over 'as-is'.  However, the method definitions on  ApexSharpApi.ApexApi.SObject are all uppercase (ex: SObject.Put() ).    Since SFDC allows case-insensitivity in apex, both SObject.Put() and SObject.put() will both work in SFDC.  However the transpiled Apex -> C# produces SObject.put(), which does not exist.  

Technically, the lower case method names are what is defined in the SFDC docs:
https://developer.salesforce.com/docs/atlas.en-us.apexcode.meta/apexcode/apex_methods_system_sobject.htm

My short term workaround for this is to simply include 'wrapper' methods on an as-needed basis:

        public object Put(string field, object value)
        {
            throw new global::System.NotImplementedException("SObject.Put");
        }

        public object put(string field, object value)
        {
            return Put(field, value);
        }
        
I don't know enough about the transpile process to understand if there is a more elegant process to handle this.

**Comment by jayonsoftware** [comment]
All methods are now loercase.
